language: php
php:
  - 8.2

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-10.phar
  - wget -O php-coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar

script:
  - mkdir -p build/logs
  - php phpunit.phar --bootstrap test/bootstrap.php test -c phpunit.xml

after_success:
  - travis_retry php coveralls.phar

sudo: false
